optimizer:
  name: adam
  lr: 1.0e-3
  weight_decay: 0

train:
  epoch: 3000
  batch_size: 4096
  save_model: false
  loss: pairwise
  test_step: 3
  reproducible: true
  seed: 2023
  patience: 10

test:
  metrics: [recall, ndcg]
  k: [5, 10, 20]
  batch_size: 1024

data:
  type: general_cf
  name: yelp


model:
  name: gccf
  # general parameters here
  keep_rate: 0.8
  embedding_size: 256

  # dataset-specific parameters here
  layer_num: 3
  reg_weight: 1.0e-6
  # for amazon
  amazon:
    layer_num: 2
    reg_weight: 1.0e-6
  # for yelp
  yelp:
    layer_num: 2
    reg_weight: 1.0e-6
  # for google
  google:
    layer_num: 3
    reg_weight: 1.0e-6

  # for steam
  steam:
    layer_num: 2
    reg_weight: 1.0e-6

