optimizer:
  name: adam
  lr: 1.0e-3
  weight_decay: 0

train:
  epoch: 3000
  batch_size: 4096
  save_model: true
  loss: pairwise
  test_step: 3
  reproducible: true
  seed: 2023
  patience: 10

test:
  metrics: [recall, ndcg]
  k: [5, 10, 20]
  batch_size: 1024
  
data:
  type: general_cf
  name: yelp

model:
  name: reform
  # general parameters here
  keep_rate: 0.8
  embedding_size: 256

  # dataset-specific parameters here
  layer_num: 3
  reg_weight: 1.0e-7
  # sample
  k: 3 

  yelp:
    layer_num: 3
    reg_weight: 1.0e-7
  
  google:
    layer_num: 3
    # keep_rate: 0.8
    # reg_weight: 1.0e-7
    reg_weight: 1.0e-6
