optimizer:
  name: adam
  lr: 1.0e-3
  weight_decay: 0

train:
  epoch: 3000
  batch_size: 4096
  save_model: false
  loss: pairwise
  test_step: 3
  reproducible: true
  seed: 2023
  patience: 10

test:
  metrics: [recall, ndcg]
  k: [5, 10, 20]
  batch_size: 1024

data:
  type: general_cf
  name: yelp

model:
  name: sgl
  # general parameters here
  keep_rate: 0.8
  embedding_size: 256
  augmentation: edge_drop

  # dataset-specific parameters here
  layer_num: 3
  reg_weight: 1.0e-5
  cl_weight: 1.0e-1
  temperature: 0.2

  yelp:
    layer_num: 3
    reg_weight: 1.0e-6
    cl_weight: 1.0e-3
    temperature: 0.1

  google:
    layer_num: 3
    reg_weight: 1.0e-6
    cl_weight: 1.0e-3
    temperature: 0.2

